apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: encuestapp-stg-area
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Emi8977/encuestapp-k8s-ECMAScript6.git
    targetRevision: main      #rama principal donde estan los archivos
    path: overlays/stg                   #es el directorio donde esta deployment.yaml en la carpeta k8s de github
  destination:
    server: https://kubernetes.default.svc
    namespace: ambiente-stg-encuestapp-mern-ECMAScript6 #el nombre del namespace que va a crear dentro del cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

